/**
 * Icons a pack can show on its cover, by their lucide name. Plain names, so the pack tools can check a
 * pack's `icon` without loading React. Adding a name here also needs its component in pack-icon.tsx.
 */
export const PACK_ICON_NAMES = [
  'flower-2',
  'fish',
  'paw-print',
  'egg',
  'tree-pine',
  'bird',
  'bug',
  'cat',
  'dog',
  'rabbit',
  'turtle',
  'squirrel',
  'snail',
  'shell',
  'snowflake',
  'sun',
  'moon',
  'star',
  'heart',
  'leaf',
  'sprout',
  'rainbow',
  'cloud',
  'rocket',
  'car',
  'tractor',
  'sailboat',
  'train-front',
  'castle',
  'crown',
  'cake',
  'ice-cream-cone',
  'apple',
  'carrot',
  'candy',
  'gift',
  'ghost',
  'music',
  'sparkles',
  'shapes',
  'tent',
] as const

export type PackIconName = (typeof PACK_ICON_NAMES)[number]
